name = "aiken-lang/nft-sentimental-based-listing-fee"
version = "0.0.0"
compiler = "v1.1.4"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/nft-sentimental-based-listing-fee'"

[repository]
user = "aiken-lang"
project = "nft-sentimental-based-listing-fee"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
